### PR TITLE
ISSUE#11 feat: add printColorList() and global colorList

### PR DESCRIPTION
**Pull request by SilverDragonOfR**
Prints a global colorList by iterating over the list.
Assuming that colorList contains hexcode of all the colors detected.
[Issue #11](https://github.com/IEEE-VIT/spectra/issues/11#issue-1935063254)

### CODE REVIEW

**Comment by Riaaggarwal06** [comment]
@SilverDragonOfR  Please make a pull request again and make the necessary changes accordingly.

**Comment by SilverDragonOfR** [comment]
Can you specify which changes?

**Comment by Riaaggarwal06** [comment]
@SilverDragonOfR Please add your code and then make a pull request again from the updated main branch.

**Comment by SilverDragonOfR** [comment]
ok will do

**Pull request closed without merging**
